name: shaulabeta
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcdde2'
    - '#e6a901'
    - '#6d6359'
    - '#a39a93'
    - '#192b2f'
  brandStrength: 0.6062413854524493
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.7523491627071053
purpose: []
