name: shaulabeta
favicon: null
layout_spectrum: 0.1428358603734523
typography_spectrum: 0.80325040477328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6062413854524493
  lightness: 0.8956288546323776
  saturation: 0.7350507087539881
  rhythmicContrast: 0.7523491627071053
purpose: []
